export const INGREDIENT_VISUALS = {
  concentrates: {
    '50-50':        { color: '#3b1a05', dark: '#1a0a02', density: 1.0, foam: false, layer: 'base', label: '50-50 Blend', opacity: 0.9 },
    '70-30':        { color: '#2c1000', dark: '#0d0400', density: 1.05, foam: false, layer: 'base', label: '70-30 Blend', opacity: 0.92 },
    'arabica':      { color: '#4a2810', dark: '#1a0a02', density: 0.95, foam: false, layer: 'base', label: '100% Arabica', opacity: 0.88 },
    'chicory':      { color: '#1f0f00', dark: '#0a0500', density: 1.1, foam: false, layer: 'base', label: 'Chicory (SIF)', opacity: 0.93 },
    'cascara':      { color: '#8a3030', dark: '#4a1515', density: 0.9, foam: false, layer: 'base', label: 'Cascara', opacity: 0.85 },
  },
  milks: {
    'dairy':        { color: '#fdf6ee', dark: '#f0e6d3', density: 0.9, foam: true, layer: 'milk', label: 'Dairy Milk', opacity: 0.75 },
    'oat':          { color: '#d4b87a', dark: '#b89e64', density: 0.85, foam: true, layer: 'milk', label: 'Oat Milk', opacity: 0.7 },
    'almond':       { color: '#e8c89a', dark: '#d4ad7a', density: 0.88, foam: false, layer: 'milk', label: 'Almond Milk', opacity: 0.72 },
    'coconut':      { color: '#f0ead0', dark: '#ddd4b0', density: 0.82, foam: false, layer: 'milk', label: 'Coconut Milk', opacity: 0.68 },
    'condensed':    { color: '#f5e6c8', dark: '#e8d4a8', density: 1.2, foam: false, layer: 'milk', label: 'Condensed Milk', opacity: 0.8 },
  },
  sweeteners: {
    'sugar_syrup':  { color: '#f0d98c', dark: '#dcc070', density: 1.0, layer: 'sweetener', label: 'Sugar Syrup', opacity: 0.5, isSyrup: true },
    'jaggery':      { color: '#7b4a20', dark: '#5a3010', density: 1.15, layer: 'sweetener', label: 'Jaggery Syrup', opacity: 0.6, isSyrup: true },
    'honey':        { color: '#d4a030', dark: '#b88420', density: 1.1, layer: 'sweetener', label: 'Wild Honey', opacity: 0.55, isSyrup: true },
    'vanilla':      { color: '#f5ecc8', dark: '#e8dbb0', density: 0.95, layer: 'sweetener', label: 'Vanilla Syrup', opacity: 0.4, isSyrup: true },
    'none':         null,
  },
  toppings: {
    'cinnamon':     { color: '#8b6914', type: 'powder', label: 'Cinnamon Powder', opacity: 0.6 },
    'cacao':        { color: '#3b1f0d', type: 'powder', label: 'Cacao Powder', opacity: 0.7 },
    'salted_caramel': { color: '#c08040', type: 'drizzle', label: 'Salted Caramel', opacity: 0.8 },
    'golden_cream': { color: '#f0d080', type: 'drizzle', label: 'Golden Cream', opacity: 0.75 },
    'honey_drizzle': { color: '#d4a030', type: 'drizzle', label: 'Honey Drizzle', opacity: 0.7 },
    'chocolate_drizzle': { color: '#3b1f0d', type: 'drizzle', label: 'Chocolate Drizzle', opacity: 0.8 },
    'almond_flakes': { color: '#d4a574', type: 'sprinkle', label: 'Almond Flakes', opacity: 0.6 },
    'coconut_flakes': { color: '#f0ead0', type: 'sprinkle', label: 'Coconut Flakes', opacity: 0.5 },
    'whipped_cream': { color: '#fff8f0', type: 'foam', label: 'Whipped Cream', opacity: 0.9 },
    'nutmeg':       { color: '#7b5a30', type: 'powder', label: 'Nutmeg Powder', opacity: 0.5 },
    'hazelnut':     { color: '#c09050', type: 'drizzle', label: 'Hazelnut Syrup', opacity: 0.7 },
    'rainbow_sprinkles': { color: '#ff88aa', type: 'sprinkle', label: 'Rainbow Sprinkles', opacity: 0.8 },
    'brown_sugar':  { color: '#8b5a2a', type: 'powder', label: 'Brown Sugar Dust', opacity: 0.5 },
    'ice':          { color: '#c0d8e8', type: 'ice', label: 'Ice Cubes', opacity: 0.6 },
    'lemon':        { color: '#e8e060', type: 'slice', label: 'Lemon Slice', opacity: 0.5 },
    'orange':       { color: '#f0a030', type: 'slice', label: 'Orange Slice', opacity: 0.5 },
  },
};

export const DRINK_OPTIONS = {
  sizes: [
    { id: 'small', name: 'Small', volume: '250ml', price: 0 },
    { id: 'standard', name: 'Standard', volume: '360ml', price: 30 },
  ],
  bases: [
    { id: '50-50', name: '50-50 Blend', price: 180, desc: 'Balanced Arabica-Robusta blend, 18h slow drip', temp: 'cold', badge: 'preferred', badgeText: 'Most Preferred' },
    { id: '70-30', name: '70-30 Blend', price: 190, desc: 'Bold Arabica-forward concentrate', temp: 'cold', badge: 'recommended', badgeText: 'Recommended' },
    { id: 'arabica', name: '100% Arabica', price: 200, desc: 'Single-origin specialty cold brew', temp: 'cold' },
    { id: 'chicory', name: 'Chicory (SIF)', price: 170, desc: 'Traditional South Indian Filter style', temp: 'cold', badge: 'preferred', badgeText: 'Most Preferred' },
    { id: 'cascara', name: 'Cascara', price: 210, desc: 'Tea-like coffee cherry infusion', temp: 'cold' },
  ],
  milks: [
    { id: 'dairy', name: 'Dairy Milk', price: 0, desc: 'Fresh frothed full-cream milk', badge: 'preferred', badgeText: 'Most Preferred' },
    { id: 'oat', name: 'Oat Milk', price: 30, desc: 'Creamy plant-based alternative', badge: 'recommended', badgeText: 'Recommended' },
    { id: 'almond', name: 'Almond Milk', price: 40, desc: 'Light nutty milk alternative' },
    { id: 'coconut', name: 'Coconut Milk', price: 40, desc: 'Tropical coconut infusion' },
    { id: 'condensed', name: 'Condensed Milk', price: 25, desc: 'Sweetened thick milk base', badge: 'recommended', badgeText: 'Recommended' },
  ],
  sweeteners: [
    { id: 'sugar_syrup', name: 'Sugar Syrup', price: 0, desc: 'Classic simple syrup', badge: 'preferred', badgeText: 'Most Preferred' },
    { id: 'jaggery', name: 'Jaggery Syrup', price: 15, desc: 'Traditional unrefined cane syrup', badge: 'recommended', badgeText: 'Recommended' },
    { id: 'honey', name: 'Wild Honey', price: 20, desc: 'Pure organic forest honey', badge: 'recommended', badgeText: 'Recommended' },
    { id: 'vanilla', name: 'Vanilla Syrup', price: 20, desc: 'Madagascar vanilla infusion' },
    { id: 'none', name: 'No Sweetener', price: 0, desc: 'Unsweetened — let the bean shine' },
  ],
  toppings: [
    { id: 'cinnamon', name: 'Cinnamon', price: 5, desc: 'Warm spice dust', type: 'powder', icon: '🌿' },
    { id: 'cacao', name: 'Cacao Powder', price: 10, desc: 'Dark cocoa finish', type: 'powder', icon: '🍫' },
    { id: 'salted_caramel', name: 'Salted Caramel', price: 20, desc: 'Sweet & salty swirl', type: 'drizzle', icon: '🍯' },
    { id: 'golden_cream', name: 'Golden Cream', price: 15, desc: 'Silky cream top', type: 'drizzle', icon: '🥛' },
    { id: 'honey_drizzle', name: 'Honey Drizzle', price: 15, desc: 'Golden honey ribbon', type: 'drizzle', icon: '🍯' },
    { id: 'chocolate_drizzle', name: 'Chocolate Drizzle', price: 15, desc: 'Rich chocolate swirl', type: 'drizzle', icon: '🍫' },
    { id: 'almond_flakes', name: 'Almond Flakes', price: 10, desc: 'Crunchy almond bits', type: 'sprinkle', icon: '🥜' },
    { id: 'coconut_flakes', name: 'Coconut Flakes', price: 10, desc: 'Toasted coconut', type: 'sprinkle', icon: '🥥' },
    { id: 'whipped_cream', name: 'Whipped Cream', price: 15, desc: 'Light fluffy cloud', type: 'foam', icon: '☁️' },
    { id: 'nutmeg', name: 'Nutmeg', price: 5, desc: 'Aromatic spice dust', type: 'powder', icon: '🌰' },
    { id: 'hazelnut', name: 'Hazelnut Syrup', price: 20, desc: 'Nutty sweet syrup', type: 'drizzle', icon: '🌰' },
    { id: 'rainbow_sprinkles', name: 'Rainbow Sprinkles', price: 5, desc: 'Colorful fun top', type: 'sprinkle', icon: '🌈' },
    { id: 'brown_sugar', name: 'Brown Sugar Dust', price: 5, desc: 'Caramelized sugar', type: 'powder', icon: '🟤' },
    { id: 'ice', name: 'Ice Cubes', price: 0, desc: 'Dense slow-melt cubes', type: 'ice', icon: '🧊' },
    { id: 'lemon', name: 'Lemon Slice', price: 10, desc: 'Fresh citrus wheel', type: 'slice', icon: '🍋' },
    { id: 'orange', name: 'Orange Slice', price: 15, desc: 'Sweet orange garnish', type: 'slice', icon: '🍊' },
  ],
};
